In [1]:
name = "Jessica"
hourly_wage= 22
hours = 40
total = hourly_wage * hours

print(f"{name} earns {total} dollars per week")

Jessica earns 880 dollars per week

In [2]:
temps = [61, 65, 72, 58, 70, 74, 68]
high = 0
for t in temps:
    if t > 65:
        high = high + 1
print (high)

4

In [3]:
def to_celsius(f):
    return (f - 32) * 5/9
print(round(to_celsius(temps[0]),1))

16.1

In [4]:
movie = {"title" : "Talladega Nights", "year" : 2006, "rating":6.6}
for key, value in movie.items():
    print(key , ":", value)

title : Talladega Nights
year : 2006
rating : 6.6

In [16]:
import pandas as pd
df = pd.read_csv("chickwts.csv")
df.describe()

       Unnamed: 0      weight
count   71.000000   71.000000
mean    36.000000  261.309859
std     20.639767   78.073700
min      1.000000  108.000000
25%     18.500000  204.500000
50%     36.000000  258.000000
75%     53.500000  323.500000
max     71.000000  423.000000

In [17]:
df.shape

(71, 3)

In [18]:
df.head()

   Unnamed: 0  weight       feed
0           1     179  horsebean
1           2     160  horsebean
2           3     136  horsebean
3           4     227  horsebean
4           5     217  horsebean

The summary shows us that there is a large spread between the chicken weights. The standard deviation is a pretty large percentage of the average weight, which can tell us that the type of food the chickens eat, will probably have great affect on their weight, before we have even looked at the complete data.