# Module 6 Lab 2: Textbook Appendix C: Create and Insert

In [1]:
import pandas as pd
import sqlite3


#create database
con = sqlite3.connect('module6lab2.db')

# Create table
create_table_query = """
CREATE TABLE customers (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
Name TEXT NOT NULL DEFAULT '',
City TEXT NOT NULL DEFAULT '',
Income INTEGER NOT NULL DEFAULT 0);
"""
con.execute(create_table_query)

pd.read_sql("SELECT name FROM sqlite_master",con)

              name
0        customers
1  sqlite_sequence

In [2]:
#creating 8 rows of data 
insert_query="""
INSERT INTO customers ( Name, City, Income)
VALUES
('Bentlei', 'Inglewood', 85000),
('Harlei', 'Hawthorne', 85000),
('Chauncey', 'Inglewood', 90000),
('Alexis', 'Torrance', 100000),
('Summer', 'Torrance', 80000),
('Flor', 'Redondo Beach', 95000),
('Cinda', 'Los Angeles', 89000),
('Jessica', 'Redondo Beach', 105000);
"""
con.execute(insert_query)
con.commit()
pd.read_sql("SELECT * FROM customers;" ,con)

   ID      Name           City  Income
0   1   Bentlei      Inglewood   85000
1   2    Harlei      Hawthorne   85000
2   3  Chauncey      Inglewood   90000
3   4    Alexis       Torrance  100000
4   5    Summer       Torrance   80000
5   6      Flor  Redondo Beach   95000
6   7     Cinda    Los Angeles   89000
7   8   Jessica  Redondo Beach  105000

## Differences I handled between MySQL and SQLite
1. Data Types:
       - MySQL uses specific types like char(35) and int(11), I used SQLite's TEXT and INTEGER types
2. Database Creation
       - MySQL uses the command CREATE DATABASE module6lab2.db, for SQLite I used sqlite3.connect('module6lab2.db')
3. Auto Increment Syntax
       - There is different syntax for auto generating ID's. MySQL uses AUTO_INCREMENT and SQLite uses AUTOINCREMENT